export const strings = {
  appName: 'SchlauBox',
  tagline: 'Verstehen. Üben. Besser werden.',
  login: 'Anmelden',
  register: 'Registrieren',
  email: 'E-Mail',
  password: 'Passwort',
  displayName: 'Anzeigename',
  logout: 'Abmelden',
  home: 'Start',
  scan: 'Scannen',
  settings: 'Einstellungen',
  consentTitle: 'Datenschutz & Einwilligung',
  consentBody:
    'SchlauBox speichert Fotos von Schultests und KI-Analysen in der EU. ' +
    'Es gibt kein Kinder-Login — nur Sie als Elternteil verwalten die Daten. ' +
    'Sie können Daten jederzeit exportieren oder löschen.',
  consentAccept: 'Ich stimme zu',
  addChild: 'Kind hinzufügen',
  childName: 'Name des Kindes',
  birthYear: 'Geburtsjahr',
  save: 'Speichern',
  cancel: 'Abbrechen',
  noChildren: 'Noch kein Kind angelegt',
  noChildrenHint: 'Legen Sie ein Kind an, um Tests zu scannen.',
  scanTest: 'Test scannen',
  fromCamera: 'Kamera',
  fromGallery: 'Galerie',
  processing: 'Wird analysiert…',
  scanFailed: 'Analyse fehlgeschlagen',
  retry: 'Erneut versuchen',
  subjects: 'Fächer',
  strengths: 'Stärken',
  weaknesses: 'Schwächen',
  analysis: 'Analyse',
  grade: 'Note',
  overrideSubject: 'Fach korrigieren',
  exportData: 'Daten exportieren',
  deleteAccount: 'Konto löschen',
  deleteAccountConfirm:
    'Alle Kinder, Scans und Analysen werden unwiderruflich gelöscht.',
  privacy: 'Datenschutzerklärung',
  recentScans: 'Letzte Tests',
  selectChild: 'Kind auswählen',
  errors: {
    generic: 'Etwas ist schiefgelaufen. Bitte erneut versuchen.',
    auth: 'Anmeldung fehlgeschlagen.',
    camera: 'Kamerazugriff verweigert.',
  },
} as const;
